Source = \
          AlreadySelectedException.class \
          AmbiguousOptionException.class \
          BasicParser.class \
          CommandLine.class \
          CommandLineParser.class \
          DefaultParser.class \
          GnuParser.class \
          HelpFormatter.class \
          MissingArgumentException.class \
          MissingOptionException.class \
          Option.class \
          OptionBuilder.class \
          OptionGroup.class \
          Options.class \
          OptionValidator.class \
          ParseException.class \
          Parser.class \
          PatternOptionBuilder.class \
          PosixParser.class \
          TypeHandler.class \
          UnrecognizedOptionException.class \
          Util.class


include $(DEV_ROOT)/Makefile